#!/usr/bin/env bash
set -ex

export DEBIAN_FRONTEND=noninteractive

apt-get update

apt-get -qqy dist-upgrade

apt-get install -qqy build-essential g++ flex bison gperf ruby perl \
  libsqlite3-dev libfontconfig1-dev libicu-dev libfreetype6 libssl-dev \
  libpng-dev libjpeg-dev python libx11-dev libxext-dev git

git clone https://github.com/ariya/phantomjs.git /phantomjs
cd /phantomjs
git checkout 2.0
./build.sh --confirm
mv bin/phantomjs /usr/local/bin
cd /
rm -rf /phantomjs

apt-get autoremove -qqy && \
apt-get clean && apt-get autoclean && \
rm -rf /usr/share/man/?? && rm -rf /usr/share/man/??_*
